### GENERAL SETTINGS ###

# Site settings
title: Aaron Drinkwater
description: "My Portfolio."
#analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "https://AaronDrinkwater.github.io"

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#171C8D" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#161616"
  link_hover: "#171C50"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: false
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: dribbble
    url:
  - title: facebook
    url:
  - title: twitter
    url:
  - title: instagram
    url:
  - title: tumblr
    url:

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address: 
  - lines:
    - Bristol, United Kingdom.
email: AaronDrinkwaterBT@gmail.com



### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Aaron Drinkwater
    position: Part Time Sales Assistant at Superdry
    text: I am a keen and passionate games developer, who's love of gaming and programming mix together well to develop games.
    img: profile_1.jpg
    social:
      - title: envelope #use for email address
        url: AaronDrinkwaterBT@gmail.com
      - title: twitter
        url: 
 
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Computer Games Technology Graduate from the University of the West of England. A wide range of skills and cross-platform development, including:  C, C++, C#, Python, Unity, Unreal Engine, DirectX, Deep Learning and much more"
